dev-api-gateway
dev-user-service
dev-payment-service
dev-wallet-service
dev-transaction-service
dev-notification-service
dev-fraud-service

...
staging-api-gateway
staging-user-service
staging-payment-service
staging-wallet-service
staging-transaction-service
staging-notification-service
staging-fraud-service
...
production-api-gateway
production-user-service
production-payment-service
production-wallet-service
production-transaction-service
production-notification-service
production-fraud-service
...
