apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet

metadata:
  name: fintech-microservices
  namespace: argocd

spec:
  goTemplate: true

  generators:
    - git:
        repoURL: https://github.com/qzee-dev/fintech-enterprise-gitops-manifest.git
        revision: main
        directories:
          - path: enterprise-gitops/environments/*/*

  template:

    metadata:
      name: '{{index .path.segments 2}}-{{index .path.segments 3}}'

    spec:
      project: fintech-microservices

      source:
        repoURL: https://github.com/qzee-dev/fintech-enterprise-gitops-manifest.git
        targetRevision: main

        path: enterprise-gitops/chart/microservice

        helm:
          valueFiles:
            - '../../../../environments/{{index .path.segments 2}}/{{index .path.segments 3}}/values.yaml'

      destination:
        server: https://kubernetes.default.svc

        namespace: '{{index .path.segments 2}}-{{index .path.segments 3}}'

      syncPolicy:
        automated:
          prune: true
          selfHeal: true

        syncOptions:
          - CreateNamespace=true
