apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: fintech-microservices
  namespace: argocd
spec:
  description: Fintech microservices GitOps project

  sourceRepos:
    - "https://github.com/qzee-dev/fintech-enterprise-gitops-manifest.git"

  destinations:
    - namespace: "dev-*"
      server: https://kubernetes.default.svc

    - namespace: "staging-*"
      server: https://kubernetes.default.svc

    - namespace: "production-*"
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
